version: '3.9'
name: 'reverse-proxy'

services:

  webserver:
    container_name: reverse-proxy
    image: nginx:stable-alpine-slim
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/:/etc/nginx/ssl/:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "com.centurylinklabs.watchtower.scope=reverse-proxy"
    networks:
      - reverse-proxy-network

  watchtower:
    container_name: reverse-proxy-watchtower
    image: containrrr/watchtower:latest
    restart: "always"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_SCOPE: 'reverse-proxy'
      WATCHTOWER_TIMEOUT: '60s'
      WATCHTOWER_SCHEDULE: '0 0 0 * * *'
      WATCHTOWER_INCLUDE_STOPPED: true
    depends_on:
      webserver:
        condition: service_started
    networks:
      - reverse-proxy-network

networks:
  reverse-proxy-network:
    external: true
